language: go
before_install:
  - go get github.com/stretchr/testify
  - go get github.com/oleiade/reflections
  - go get github.com/lib/pq
  - go get github.com/guregu/null
  - go get github.com/satori/go.uuid
go:
  - 1.3
  - 1.4
  - 1.5
script: make test
